# Generated by Django 3.0.8 on 2020-07-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200728_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='default_product.jpg', upload_to='products'),
        ),
    ]
