# Generated by Django 3.0.8 on 2020-07-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200728_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('crystal', 'Crystal'), ('statue', 'Stone Sculpture'), ('pebble', 'Pebble')], default='Crystal', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
