# Generated by Django 3.0.8 on 2020-07-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200729_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('hot', 'hot'), ('exclusive', 'Exclusive')], max_length=10, null=True),
        ),
    ]
