# Generated by Django 3.0.8 on 2020-08-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200826_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='fname',
            field=models.CharField(default='Jhon', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='lname',
            field=models.CharField(default='Doe', max_length=100),
        ),
    ]
